title: Alex Musumeci # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing a Graduate Certificate in Data Science at RMIT.
  <br><br>
  I am a Project Officer for Parks Victoria, focusing on land and park management where my newly aquired data skills are being used to shape the future management of the Yarra River. Other areas of expertise include aquatic ecology and marine biology. 
  <br><br>
  <a href="https://au.linkedin.com/in/alex-musumeci-104661107">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
