title: Alex Musumeci # your name (or website title) here
logo: "/images/portrait_profesh.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have recently completed a Graduate Certificate in Data Science at RMIT.
  <br><br>
  I am an experienced envrionmental professional, my current focus is on waterways management, where my newly acquired data skills are being used to shape the future management of the Yarra River.
  <br><br>
  <a href="https://au.linkedin.com/in/alex-musumeci-104661107">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
